<?php
// $Id$

function simple_geo_menu() {
  $items = array();
  $items['node/%node/map'] = array(
    'title' => t('Map'),
    'page callback' => 'simple_geo_view_position',
    'page arguments' => array(1),
    'access callback' => 'node_access',
    'access arguments' => array('view', 1),
    'type' => MENU_LOCAL_TASK,
    'file' => 'simple_geo_fallback_functions.php',
    'weight' => 0,
  );
  return $items;
}

function simple_geo_perm() {
  return array(
    'edit own nodes area', 'edit own nodes position', 'edit all areas', 'edit all positions'
  );
}

function simple_geo_guess_position() {
  return '';
}

function simple_geo_form_alter($form, $form_state, $form_id) {
  if ($form_id == 'node_type_form') {
    $type = $form['#node_type']->type;
    $set = array(
      '#type' => 'fieldset',
      '#title' => t('Geographic fields'),
      '#collapsible' => TRUE);
    
    $set['allow_position'] = array(
      '#type' => 'checkbox',
      '#default_value' => variable_get('allow_position_'. $type, FALSE),
      '#title' => t('Use position'),
    );
    
    $set['allow_area'] = array(
      '#type' => 'checkbox',
      '#default_value' => variable_get('allow_area_'. $type, FALSE),
      '#title' => t('Use area'),
    );
    
    $form['simple_geo'] = $set;
  }
  else if ($form['#id'] == 'node-form'){
    $node = $form['#node'];
    global $user;
    
    if ($form_id == $node->type .'_node_form') {
      $allow_position = variable_get('allow_position_'. $node->type, FALSE);
      $allow_area = variable_get('allow_area_'. $node->type, FALSE);
      
      $set = array(
        '#type' => 'fieldset',
        '#attributes' => array('id'=>'simple_geo_form'),
        '#title' => t('Position'),
        '#collapsible' => TRUE);
      $editing = FALSE;
      
      if ($allow_position && (user_access('edit all positions') || 
          ($node->uid == $user->uid && user_access('edit own node position')))) {
        if (!isset($node->simple_geo_position)) {
          $position = simple_geo_guess_position($node);
        }
        else {
          $position = $node->simple_geo_position;
        }

        $set['simple_geo_position'] = array(
          '#type' => 'textfield',
          '#title' => t('Position'),
          '#attributes' => array('class'=>'simple-geo-position'),
          '#default_value' => $position,
          '#weight' => 1,
        );
        
        $editing = true;
      }
      
      if ($allow_area && (user_access('edit all areas') || 
          ($node->uid == $user->uid && user_access('edit own node area')))) {
        $area = '';
        if (isset($node->simple_geo_area)) {
          $area = $node->simple_geo_area;
        }
        
        $set['simple_geo_area'] = array(
          '#type' => 'textarea',
          '#title' => t('Area'),
          '#attributes' => array('class'=>'simple-geo-area'),
          '#default_value' => $area,
          '#weight' => 2,
        );
        
        $editing = true;
      }
      
      if ($editing) {
        drupal_add_js(drupal_get_path('module', 'simple_geo') .'/js/node_edit.js', 'module', 'header');
        $set['map_placeholder'] = array(
          '#type' => 'markup',
          '#value' => '<div class="map-placeholder"></div>',
          '#weight' => -1,
        );
        $form['simple_geo'] = $set;
      }
    }
  }
}

function simple_geo_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  $allow_position = variable_get('allow_position_'. $node->type, FALSE);
  $allow_area = variable_get('allow_area_'. $node->type, FALSE);
  
  switch($op) {
    case 'delete':
      simple_geo_delete_position($node->nid);
      simple_geo_delete_area($node->nid);
      break;
    case 'update':
    case 'insert':
      global $user;
      
      if (!empty($node->simple_geo_position) && $allow_position && (user_access('edit all positions') || 
          ($node->uid == $user->uid && user_access('edit own node position')))) {
        simple_geo_set_position($node->nid, $node->simple_geo_position);
      }
      
      if (!empty($node->simple_geo_area) && $allow_area && (user_access('edit all areas') || 
          ($node->uid == $user->uid && user_access('edit own node area')))) {
        simple_geo_set_area($node->nid, $node->simple_geo_area);
      }
      
      simple_geo_update_cache($node->nid);
      break;
    case 'load':
      if ($allow_position) {
        $node->simple_geo_position = simple_geo_position($node->nid);
      }
      if ($allow_area) {
        $node->simple_geo_area = simple_geo_area($node->nid);
      }
      break;
    case 'view':
      $map_view = '';
      if (!empty($node->simple_geo_position)) {
        $coords = explode(' ', $node->simple_geo_position);
        $map_view .= '<div class="node-map"><a rel="map" title="'. 
          t('Map for @name', array('@name'=>$node->title)) .'" href="'. url('node/'. $node->nid .'/map/') .'">'. 
          t('Map for @name', array('@name'=>$node->title)) .'</a></div>';
        $map_view .= '<div class="geo">'. t('Position:') .'
         <span class="latitude">'. $coords[0] .'</span> 
         <span class="longitude">'. $coords[1] .'</span>
        </div>';
        
      }
      
      if (!empty($node->simple_geo_area)) {
        $map_view .= '<script type="text/javascript">var node_'. $node->nid .'_position="'. $node->simple_geo_position .'";'.
          'var node_'. $node->nid .'_area="'. $node->simple_geo_area .'";</script>';
      }
      
      $node->content[] = array(
        '#weight' => -1,
        '#value' => $map_view,
      );
      break;
  }
}

function simple_geo_position($nid) {
  $res = db_query("SELECT AsText(position) FROM {simple_geo_position} WHERE nid = %d", $nid);
  if ($wkt = db_result($res)) {
    return simple_geo_clean_wkt('point', $wkt);
  }
}

function simple_geo_area($nid) {
  $res = db_query("SELECT AsText(area) FROM {simple_geo_area} WHERE nid = %d", $nid);
  if ($wkt = db_result($res)) {
    return simple_geo_clean_wkt('polygon', $wkt);
  }
}

/**
 * Updates the cache for the spatial relationship between points and polygons
 *
 * @param int $nid The node to update the cache for
 * @param string $op The cache type to update. 'area', 'point' or 'all', defaults to 'all'
 *
 * @return void
 * @author Hugo Wetterberg
 **/
function simple_geo_update_cache($nid, $op='all') {
  $updates = array();
  
  if ($op=='all') {
    //Delete all cache entries
    db_query("DELETE FROM {simple_geo_in_area} WHERE point_nid = %d OR area_nid = %d", $nid, $nid);
  }
  
  //Refresh cache for position
  if ($op!='area') {
    if ($op!='all') {
      //Delete all position cache entries
      db_query("DELETE FROM {simple_geo_in_area} WHERE point_nid = %d", $nid);
    }
    $position = simple_geo_position($nid);
    if ($position) {
      $p_array = simple_geo_coordinates_to_array($position);
      $res = db_query("SELECT nid, AsText(area) as area_wkt 
        FROM {simple_geo_area}
        WHERE Contains(area, GeomFromText('%s'))", simple_geo_to_wkt('point', $position));
      $areas = array();
      while ($bb_match = db_fetch_object($res)) {
        $a_coords = simple_geo_clean_wkt('polygon', $bb_match->area_wkt);
        if (simple_geo_point_in_polygon($a_coords, $p_array)) {
          $updates[$nid] = $bb_match->nid;
        }
      }
    }
  }
  
  //Refresh cache for area
  if ($op!='point') {
    if ($op!='all') {
      //Delete all area cache entries
      db_query("DELETE FROM {simple_geo_in_area} WHERE area_nid = %d", $nid);
    }
    $area = simple_geo_area($nid);
    if ($area) {
      $a_array = simple_geo_coordinates_to_array($area);
      $res = db_query("SELECT nid, AsText(position) as position_wkt 
        FROM {simple_geo_position}
        WHERE Contains(GeomFromText('%s'), position)", simple_geo_to_wkt('polygon', $area));
      $points = array();
      while ($bb_match = db_fetch_object($res)) {
        $p_coords = simple_geo_clean_wkt('point', $bb_match->position_wkt);
        if (simple_geo_point_in_polygon($a_array, $p_coords)) {
          $updates[$bb_match->nid] = $nid;
        }
      }
    }
  }
  
  //Add all new cache items
  if(count($updates)) {
    $handlers = module_implements('simple_geo_inside');
    $query = "INSERT INTO {simple_geo_in_area}(point_nid, area_nid) VALUES";
    foreach ($updates as $point => $area) {
      foreach($handlers as $module) {
        call_user_func($module .'_simple_geo_inside', $point, $area);
      }
      $query .= '('. $point .','. $area .'),';
    }
    db_query(trim($query,','));
  }
}

function simple_geo_point_on_vertex($point, $vertices) {
  foreach($vertices as $vertex) {
    if ($point == $vertex) {
      return true;
    }
  }
}

/**
 * Checks if a nodes point is inside a nodes area
 *
 * @param int $area_nid The nid of the area node
 * @param int $position_nid The nid of the position node
 *
 * @return void
 * @author Hugo Wetterberg
 **/
function simple_geo_contains($area_nid, $position_nid) {
  $res = db_query("SELECT COUNT(*) FROM {simple_geo_in_area} WHERE point_nid=%d AND area_nid=%d", $position_nid, $area_nid);
  return db_result($res)==1;
}

/**
 * Function that returns the necessary information for integrating with the
 * spatial relationship cache
 *
 * @return void
 * @author Hugo Wetterberg
 **/
function simple_geo_db_info() {
  return array(
    'table' => 'simple_geo_in_area',
    'position' => 'point_nid',
    'area' => 'area_nid',
  );
}

function simple_geo_point_in_polygon($polygon, $point) {
  // Transform string coordinates into arrays with lat and long values
  if (!is_array($point)) {
    $point = simple_geo_coordinates_to_array($point);
  }
  $vertices = $polygon; 
  if (!is_array($vertices)) {
    $vertices = simple_geo_coordinates_to_array($vertices);
  }
  
  // Check if the point sits exactly on a vertex
  if (simple_geo_point_on_vertex($point, $vertices) == true) {
    return true;
  }
  
  // Check if the point is inside the polygon or on the boundary
  $intersections = 0; 
  $vertices_count = count($vertices);
  
  for ($i=1; $i < $vertices_count; $i++) {
    $vertex1 = $vertices[$i-1]; 
    $vertex2 = $vertices[$i];
    if ($vertex1[1] == $vertex2[1] 
        and $vertex1[1] == $point[1] 
        and $point[0] > min($vertex1[0], $vertex2[0]) 
        and $point[0] < max($vertex1[0], $vertex2[0])) { // Check if point is on an horizontal polygon boundary
      return true;
    }
    if ($point[1] > min($vertex1[1], $vertex2[1]) 
        and $point[1] <= max($vertex1[1], $vertex2[1]) 
        and $point[0] <= max($vertex1[0], $vertex2[0]) 
        and $vertex1[1] != $vertex2[1]) { 
      $xinters = ($point[1] - $vertex1[1]) * ($vertex2[0] - $vertex1[0]) / ($vertex2[1] - $vertex1[1]) + $vertex1[0]; 
      
      if ($xinters == $point[0]) { // Check if point is on the polygon boundary (other than horizontal)
        return true;
      }
      if ($vertex1[0] == $vertex2[0] || $point[0] <= $xinters) {
        $intersections++; 
      }
    } 
  } 
  // If the number of edges we passed through is even, then it's in the polygon. 
  if ($intersections % 2 != 0) {
    return true;
  } else {
    return false;
  }
}

function simple_geo_delete_position($nid) {
  db_query("DELETE FROM {simple_geo_position} WHERE nid = %d", $nid);
}

function simple_geo_delete_area($nid) {
  db_query("DELETE FROM {simple_geo_area} WHERE nid = %d", $nid);
}

function simple_geo_set_position($nid, $position) {
  simple_geo_delete_position($nid);
  db_query("INSERT INTO {simple_geo_position}(nid, position)
    VALUES(%d, GeomFromText('%s'))", $nid, simple_geo_to_wkt('point', $position));
}

function simple_geo_set_area($nid, $area) {
  simple_geo_delete_area($nid);
  db_query("INSERT INTO {simple_geo_area}(nid, area)
    VALUES(%d, GeomFromText('%s'))", $nid, simple_geo_to_wkt('polygon', $area));
}

function simple_geo_to_wkt($type, $coord) {
  switch($type) {
    case 'point':
      return 'POINT('. $coord .')';
    case 'polygon':
      return 'POLYGON(('. $coord .'))';
  }
}

function simple_geo_coordinates_to_array($coords) {
  $pairs = explode(',', $coords);
  $pair_count = count($pairs);
  for($i=0; $i<$pair_count; $i++) {
    $pairs[$i] = explode(' ',$pairs[$i]);
  }
  if ($pair_count==1) {
    return $pairs[0];
  }
  else {
    return $pairs;
  }
}

function simple_geo_custom_separators($coords, $pair=',', $coordinate=' ') {
  if($pair==',' && $coordinate==' ') {
    return $coords;
  }
  $pairs = simple_geo_coordinates_to_array($coords);
  $pair_count = count($pairs);
  if ($pair_count && !is_array($pairs[0])) {
    return join($coordinate, $pairs);
  }
  for($i=0; $i<$pair_count; $i++) {
    $pairs[$i] = join($coordinate, $pairs[$i]);
  }
  return join($pair,$pairs);
}

function simple_geo_clean_wkt($type, $wkt) {
  switch($type) {
    case 'point':
      return preg_replace('/^POINT\((.+)\)$/', '$1', $wkt);
    case 'polygon':
      return preg_replace('/^POLYGON\(\((.+)\)\)$/', '$1', $wkt);
  }
}

function simple_geo_meta_tags($node) {
  $meta = '';
  if (!empty($node->simple_geo_position)) {
    $c = explode(' ', $node->simple_geo_position);
    $meta .= '<meta name="geo.placename" content="'. check_plain($node->title) .'" />';
    $meta .= '<meta name="icbm" content="'. join(', ', $c) .'" />';
    $meta .= '<meta name="geo.position" content="'. join('; ', $c) .'" />';
  }
  if (!empty($node->simple_geo_area)) {
    $meta .= '<meta name="geo.extent" content="'. $node->simple_geo_area .'" />';
  }
  return $meta;
}